### PR TITLE
Facade implementation

### PR DESCRIPTION
**Pull request by vecerap**
Created facades for entities

**Things to discuss:** 

1. Should I implement method for getting `AnswerResultModel` based on question and user in answer facade? Or is it enough when I do mapping of these models in question facade with all questions related to the quiz id?
2. Should `IsCorrect` in AnswerResultModel represent, that answer **is marked as correct** from the point of view of the quiz assignee or if the answer is correct from the point of view who the answer was answering?
3. Should I perform mapping of all model's attributes event if in given context is not some atribute necessary? Eg. on `QuestionDetailModel` atribute `IsAnswered` in a context of general search is in my opinion not needed to be mapped, because the function would then need another parameter in form of user id for confirmation whether the user has answered the question. The idea is to make a new method for a `GetAnswersForUser` where you would need to fill the user id in order to obtain the collection of questions.
4. Should I include for nearly every case a mandatory atribute right inside the model? For example where I made this change was in answer model, where it makes sense to include the question id right during the creation, because it does not make sense to have freely floating answer without appended question.
5. Do I have to enforce unique order of answer on every answer submit? (except for order 0 which means order is not used)

### CODE REVIEW

**Comment by brtkkndrl** [comment]
1. I don't think it's necessary now, should be enough to get user answer results to questions in a quiz.
2. Don't understand, Can you give example use cases for this model?
3. I think you shouldn't do any unnecessary mapping. Do we even need `GetAnswersForUser`? If it's supposed to get questions that a user answered, then I think getting question answers in a quiz by user should be enough.
4. Shouln't models just contain the information you are going to use? If we get answer models by question ID, we don't need this question ID to be present in all the models.
5. Then it would not be possible to change order of answers once they are saved. How about seperate method to `setOrderOfAnswers`, where you send all answers with order and then you check if orders are unique and range from 1 to N, with increments of 1?

**Comment by KoubaFromPucks** [comment]
1. I think that we do not need it.
2. I think that IT should indicate that answer Is marked as correct, because in other case it could be confusing when using same name of the attribute that is related to one entity, but has different meaning.
3. I think it would be better not to do that 
4. I agree with Bartosz
5. I thing that it is not bad idea. When the type of question  is to order items. I  other type it is not important.

**Comment by vecerap** [comment]
> 1. I don't think it's necessary now, should be enough to get user answer results to questions in a quiz.
> 2. Don't understand, Can you give example use cases for this model?
> 3. I think you shouldn't do any unnecessary mapping. Do we even need `GetAnswersForUser`? If it's supposed to get questions that a user answered, then I think getting question answers in a quiz by user should be enough.
> 4. Shouln't models just contain the information you are going to use? If we get answer models by question ID, we don't need this question ID to be present in all the models.
> 5. Then it would not be possible to change order of answers once they are saved. How about seperate method to `setOrderOfAnswers`, where you send all answers with order and then you check if orders are unique and range from 1 to N, with increments of 1?

for number two you can image having green checkmark / red cross next to every answer indicating, whether the user has this response right or wrong - this is the current implementation, but I am not sure, if this would not make things more confusing. Or use the same argument function as it is currently in entites, meaning that the answer is marked right or wrong and after the user response is determined whether it has the question right or wrong (or partly wrong, it is up to the API and FE)

For number three - yeah ok, I will take a look at it.

4. No you did not understand, I mean when I want to save an updated or newly created entity in database, I am not referring to the retrieval of the information
5. I will think about it

**Comment by brtkkndrl** [comment]
TWO. Then I think it should mark if the answer is right or wrong in relation to the question.
FOUR. What if facade would require questionId when saving answer model?

**Comment by vecerap** [comment]
> TWO. Then I think it should mark if the answer is right or wrong in relation to the question. FOUR. What if facade would require questionId when saving answer model?
@BRTEK007 
4. By including question Id inside the model, you can override the `Save` function inside the base class. When I would want to use it as parameter inside a function, you would either throw an exception on ordinary save function (because the relation is required as answer is kind of a weak entity), or make two calls to the database, one with save the model using `Save `function and second to save the Id in `AnswerEntity` with other function

**Pull request closed without merging**
